use boilerplate script code from gradlew script to improve detection of Java executable

diff --git a/bin/logentry b/bin/logentry
--- a/bin/logentry
+++ b/bin/logentry
@@ -1,19 +1,91 @@
 #!/bin/bash
-# An executable shell script wrapper around a Java Command Line Utility
-# for making log entries 
+
+#!/bin/bash
+# ##########################################################################
+#
+# A logentrycli wrapper script for Windows
+#
+# Much of this script's boilerplate was shamelessly copied from 
+# the gradlew shell script
+# ##########################################################################
+
+# Attempt to set APP_HOME
+
+# Resolve links: $0 may be a link
+app_path=$0
+
+# Need this for daisy-chained symlinks.
+while
+    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
+    [ -h "$app_path" ]
+do
+    ls=$( ls -ld "$app_path" )
+    link=${ls#*' -> '}
+    case $link in             #(
+      /*)   app_path=$link ;; #(
+      *)    app_path=$APP_HOME$link ;;
+    esac
+done
+
+# This is normally unused
+# shellcheck disable=SC2034
+APP_BASE_NAME=${0##*/}
+APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit
+
+# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
+DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'
+
+# Use the maximum available, or set MAX_FD != -1 to use that value.
+MAX_FD=maximum
+
+warn () {
+    echo "$*"
+} >&2
+
+die () {
+    echo
+    echo "$*"
+    echo
+    exit 1
+} >&2
+
+# OS specific support (must be 'true' or 'false').
+cygwin=false
+msys=false
+darwin=false
+nonstop=false
+case "$( uname )" in                #(
+  CYGWIN* )         cygwin=true  ;; #(
+  Darwin* )         darwin=true  ;; #(
+  MSYS* | MINGW* )  msys=true    ;; #(
+  NONSTOP* )        nonstop=true ;;
+esac
 
 
-#Edit the path below to indicate the location where the
-#LogentryCLI.jar file resides.
-JAR=/site/ace/certified/apps/logentrycli/pro/LogentryCLI.jar
 
-# Test if user has java in path
-path_to_executable=$(which java)
-if [ $? -eq 0 -a -x "$path_to_executable" ] ; then
-   java -jar $JAR "$@"
+# Determine the Java command to use to start the JVM.
+if [ -n "$JAVA_HOME" ] ; then
+    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
+        # IBM's JDK on AIX uses strange locations for the executables
+        JAVACMD=$JAVA_HOME/jre/sh/java
+    else
+        JAVACMD=$JAVA_HOME/bin/java
+    fi
+    if [ ! -x "$JAVACMD" ] ; then
+        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME
+
+Please set the JAVA_HOME variable in your environment to match the
+location of your Java installation."
+    fi
 else
-   echo "Error: Java executable not found."
-   echo "Please make sure java is set in your PATH environment variable."
-   exit 1
+    JAVACMD=java
+    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
+
+Please set the JAVA_HOME variable in your environment to match the
+location of your Java installation."
 fi
+
+
+JAR=${APP_HOME}/../lib/logentrycli.jar
+exec "$JAVACMD" -jar "$JAR" "$@"
 
